In [1]:
import pandas as pd
import re
import seaborn
import numpy as np

In [2]:
df = pd.read_csv('testNine.csv')

In [3]:
df.shape

(281, 17)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             281 non-null    int64
 1   id                     281 non-null    int64
 2   offset                 240 non-null    float64
 3   xmin                   281 non-null    int64
 4   ymin                   281 non-null    int64
 5   xmax                   281 non-null    int64
 6   ymax                   281 non-null    int64
 7   label                  281 non-null    object
 8   car_direction          240 non-null    object
 9   car_curv               240 non-null    float64
 10  lane_Two_firstPoint    243 non-null    object
 11  lane_Two_midPoint      243 non-null    object
 12  lane_Two_lastPoint     243 non-null    object
 13  lane_Three_firstPoint  240 non-null    object
 14  lane_Three_midPoint    240 non-null    object
 15  lane_Three_lastPoint   240 non-null    object
 16  distance               281 non-null    float64
dtypes: float64(3), int64(6), object(8)
memory usage: 37.4+ KB

In [5]:
df

,Unnamed: 0,id,offset,xmin,ymin,xmax,ymax,label,car_direction,car_curv,lane_Two_firstPoint,lane_Two_midPoint,lane_Two_lastPoint,lane_Three_firstPoint,lane_Three_midPoint,lane_Three_lastPoint,distance
0,2,2,0.178726,555,5,684,1277,car,F,3410.357597,"596, 402","415, 561","228, 720","684, 408","845, 478","993, 543",1278.524540
1,3,2,0.178726,366,615,413,671,car,F,3410.357597,"596, 402","415, 561","228, 720","684, 408","845, 478","993, 543",73.109507
2,4,3,0.192303,365,615,412,671,car,F,1279.078799,"595, 402","414, 561","228, 720","697, 408","845, 478","993, 543",73.109507
3,5,3,0.192303,554,2,682,1276,car,F,1279.078799,"595, 402","414, 561","228, 720","697, 408","845, 478","993, 543",1280.413996
4,6,4,0.170745,363,614,409,670,car,F,2946.291478,"590, 402","412, 561","227, 720","678, 402","839, 472","993, 543",72.470684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,335,182,NaN,67,493,524,1278,car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,908.335841
277,336,183,NaN,83,521,523,1278,car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,875.584947
278,337,184,NaN,93,531,524,1278,car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,862.421011
279,338,185,NaN,103,541,523,1279,truck,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,849.143097
280,339,186,NaN,116,562,522,1279,car,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,823.969053

In [6]:
# for i in range(1,50):
#     df[f'point{i}'] =

In [7]:
# for i in df['lane2_points']:
#     pointList = []
#     foundList = re.findall(r'\(\d{3},\s\d{3}\)',i)
#     for j in range(len(foundList)):
#         df.insert(j, f'point{j}', foundList[j])
# #         print(foundList[j])
#     print(i)

In [8]:
# # lane Two
# firstPointList = []
# midPointList = []
# lastPointList = []

# for i in df['lane2_points']:
#     foundlist = re.findall(r'\(\d{3},\s\d{3}\)',i)
#     if foundlist == []:
#         firstPointList.append(None)
#         midPointList.append(None)
#         lastPointList.append(None)
#     else:
#         firstPointList.append(foundlist[0].strip(r'()'))
#         midPointList.append(foundlist[int(len(foundlist)/2)].strip(r"()"))
#         lastPointList.append(foundlist[-1].strip(r"()"))
# #     print(foundpat.group().strip(r'()'))
# df['lane_Two_firstPoint'] = firstPointList
# df['lane_Two_midPoint'] = midPointList
# df['lane_Two_lastPoint'] = lastPointList

In [9]:
# # lane Three 
# firstPointList = []
# midPointList = []
# lastPointList = []
# for i in df['lane3_points']:
#     foundlist = re.findall(r'\(\d{3},\s\d{3}\)',i)
#     if foundlist == []:
#         firstPointList.append(None)
#         midPointList.append(None)
#         lastPointList.append(None)
#     else:
#         firstPointList.append(foundlist[0].strip(r'()'))
#         midPointList.append(foundlist[int(len(foundlist)/2)].strip(r"()"))
#         lastPointList.append(foundlist[-1].strip(r"()"))
# #     print(foundpat.group().strip(r'()'))
# df['lane_Three_firstPoint'] = firstPointList
# df['lane_Three_midPoint'] = midPointList
# df['lane_Three_lastPoint'] = lastPointList
# df = df.drop(df[(df['car_curv'] > 10000)].index)
# df = df.drop(["lane1_detected",
#              "lane2_detected",
#              "lane3_detected",
#              "lane4_detected",
#              "lane1_points",
#              "lane2_points",
#              "lane3_points",
#              "lane4_points"], axis=1)

In [10]:
df.lane_Three_firstPoint.loc

In [11]:
from numpy import ones,vstack
from numpy.linalg import lstsq
points = [(1,5),(3,4)]
x_coords, y_coords = zip(*points)
A = vstack([x_coords,ones(len(x_coords))]).T
m, c = lstsq(A, y_coords)[0]
print("Line Solution is y = {m}x + {c}".format(m=m,c=c))

Line Solution is y = -0.5000000000000002x + 5.5

C:\Users\Rayan\AppData\Local\Temp\ipykernel_24972\299331317.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  m, c = lstsq(A, y_coords)[0]

In [12]:
# df = df.drop(["lane1_detected",
#              "lane2_detected",
#              "lane3_detected",
#              "lane4_detected",
#              "lane1_points",
#              "lane2_points",
#              "lane3_points",
#              "lane4_points"], axis=1)

KeyError: "['lane1_detected', 'lane2_detected', 'lane3_detected', 'lane4_detected', 'lane1_points', 'lane2_points', 'lane3_points', 'lane4_points'] not found in axis"

In [ ]:
# Q1 = np.percentile(df['car_curv'], 25, interpolation = 'midpoint')

# Q3 = np.percentile(df['car_curv'], 75, interpolation = 'midpoint')

# IQR = Q3 - Q1
               
# print('lower limit of outliers ', Q1 - 1.5*(IQR))
# print('higher limit of outliers', Q3 + 1.5*(IQR))

df = df.drop(df[(df['car_curv'] > 10000)].index)

In [ ]:
seaborn.boxplot(df, x='car_curv')

In [ ]:
pd.set_option('display.max_columns', None)
df